config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get '/home/about' => 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: {minimum:2, maximum:20}
  validates :introduction, length: {maximum:50}

  has_many :books, dependent: :destroy

  attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully created"
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    if @user == current_user
      @books = Book.all
    else
      @user = current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully updated"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "successfully deleted"
    redirect_to books_path
  end

  private

    def book_params
      params.require(:book).permit(:title, :body, :user_id)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully updated"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %> error.
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Update Book' %>
<% end %>
<%= link_to 'Show', "/books/#{@book.id}" %></td>
<%= link_to "Back", "/books" %>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <% if User.find(book.user_id).profile_image_id != nil %>
                  <%= link_to (attachment_image_tag User.find(book.user_id), :profile_image, :fill, 50, 50, format: 'jpeg'), user_path(book.user_id) %>
                <% else %>
                  <%= link_to (image_tag asset_path("noimage.png"), alt:"noimage", size:"50x50"), user_path(book.user_id) %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: @user, book: nil %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <% if User.find(@book.user_id).profile_image_id != nil %>
                <%= link_to (attachment_image_tag User.find(@book.user_id), :profile_image, :fill, 50, 50, format: 'jpeg'), user_path(@book.user_id) %>
              <% else %>
                <%= link_to (image_tag asset_path("noimage.png"), alt:"noimage", size:"50x50"), user_path(@book.user_id) %>
              <% end %>
              <br>
              <%= link_to User.find(@book.user_id).name, user_path(@book.user_id) %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <td>
              <% if @book.user_id == current_user.id %>
                <%= link_to "Edit", edit_book_path(@book), class:"btn btn-success" %>
                <%= link_to "Destroy", book_path(@book), method:"delete", data:{confirm:'Are you sure?'}, class:"btn btn-danger" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="row">
  <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
</div>

app/views/homes/top.html.erb
<div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
    <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p> about various books!</p>
    <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <%= link_to "Log in",  "/users/sign_in", class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
      </div>
      <div class="row">
        <%= link_to "Sign up", "/users/sign_up", class:"btn btn-success btn-sm btn-block sign_up" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/cf8c179971.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <span><%= link_to "Bookers", "/", class:"navbar-brand" %></span>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to " Home", user_path(current_user.id), class: 'fas fa-home nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to " Users", '/users', class: 'fas fa-users nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to " Books", '/books', class: 'fas fa-book-open nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to " Log out", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-white' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to " Home", '/', class: 'fas fa-home nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to " About", '/home/about', class: 'fas fa-link nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to " Sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to " Log in", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-white' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
      <p><%= flash[:notice] %></p>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_sidebar.html.erb
<div class="col-md-3">
  <% if book.nil? == false %>
    <% if book.errors.any? %>
      <%= book.errors.count %> error.
      <% book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
  <% else %>
    <% book = Book.new %>
  <% end %>
  <h2>User info</h2>
  <% if user.profile_image_id != nil %>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg' %>
  <% else %>
    <%= image_tag asset_path("noimage.png"), alt:"noimage", size:"100x100" %>
  <% end %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to "", edit_user_path(user.id), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, local:true do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <% if @user.errors.any? %>
      <%= @user.errors.count %> error.
      <% @user.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
    <%= form_with model: @user, local:true do |f| %>
      <h4>Name</h4>
      <%= f.text_field :name %>
      <h4>Image</h4>
      <%= f.attachment_field :profile_image %>
      <h4>Introduction</h4>
      <%= f.text_area :introduction %>
      <br>
      <%= f.submit 'Update User', class:"btn btn-secondary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <% if user.profile_image_id != nil %>
                  <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg' %>
                <% else %>
                  <%= image_tag asset_path("noimage.png"), alt:"noimage", size:"50x50" %>
                <% end %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <% if book.user_id == @user.id %>
            <tr>
              <td>
                <% if User.find(book.user_id).profile_image_id != nil %>
                  <%= link_to (attachment_image_tag User.find(book.user_id), :profile_image, :fill, 50, 50, format: 'jpeg'), user_path(book.user_id) %>
                <% else %>
                  <%= link_to (image_tag asset_path("noimage.png"), alt:"noimage", size:"50x50"), user_path(book.user_id) %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>